# gocd.yaml

pipelines:
  discord-alert:
    group: defaultGroup
    materials:
      my-git-repo2:
        git: https://github.com/dalso0418/gocd-task
        branch: main
    stages:
      - execute-remote-command:
          jobs:
            run-ls-on-server:
              environment_variables:
                SERVER_KEY_B64: "{{SECRET:[ssh-key][gocd_deploy_key]}}"
                DISCORD_WEBHOOK: "{{SECRET:[discord-webhook][discord-webhookurl]}}"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        mkdir -p ./temp
                        echo "$SERVER_KEY_B64" | base64 --decode > ./temp/id_rsa_remote
                        chmod 600 ./temp/id_rsa_remote
                        ssh -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ./temp/id_rsa_remote root@192.168.1.118 'echo "--- 원격 서버 파일 목록 ---"; ls -la' > task_output.log
                        rm -rf ./temp

                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                      - -c
                      - |
                        TASK_RESULT=$(cat task_output.log)
                        
                        # JSON payload를 jq로 생성
                        JSON_PAYLOAD=$(jq -n \
                          --arg pipeline_name "$GO_PIPELINE_NAME" \
                          --arg pipeline_counter "$GO_PIPELINE_COUNTER" \
                          --arg pipeline_url "$GO_SERVER_URL/go/pipelines/$GO_PIPELINE_NAME/$GO_PIPELINE_COUNTER/$GO_STAGE_NAME/$GO_STAGE_COUNTER" \
                          --arg stage_name "$GO_STAGE_NAME" \
                          --arg job_name "$GO_JOB_NAME" \
                          --arg task_result "$TASK_RESULT" \
                          '{
                            "embeds": [
                              {
                                "title": "✅ 파이프라인 실행 성공: \($pipeline_name)",
                                "description": "**- 파이프라인:** [\($pipeline_name)/\($pipeline_counter)](\($pipeline_url))\n**- 스테이지:** \($stage_name)\n**- 잡:** \($job_name)",
                                "color": 3066993,
                                "fields": [
                                  {
                                    "name": "📜 원격 작업 실행 결과",
                                    "value": ("```bash\n" + $task_result + "\n```")
                                  }
                                ]
                              }
                            ]
                          }'
                        )
                        
                        # Discord Webhook으로 전송
                        curl -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" "$DISCORD_WEBHOOK"
                                      
              on_cancel:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        JSON_PAYLOAD=$(printf '{
                          "embeds": [{
                            "title": "❌ 파이프라인 실행 실패: %s",
                            "description": "**- 파이프라인:** [%s/%s](%s)\n**- 스테이지:** %s\n**- 잡:** %s",
                            "color": 15158332
                          }]
                        }' "${GO_PIPELINE_NAME}" "${GO_PIPELINE_NAME}" "${GO_PIPELINE_COUNTER}" "${GO_SERVER_URL}/go/pipelines/${GO_PIPELINE_NAME}/${GO_PIPELINE_COUNTER}/${GO_STAGE_NAME}/${GO_STAGE_COUNTER}" "${GO_STAGE_NAME}" "${GO_JOB_NAME}")

                        curl -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" "$DISCORD_WEBHOOK"
