pipelines:
  discord-alert:
    group: defaultGroup
    materials:
      my-git-repo2:
        git: https://github.com/dalso0418/gocd-task
        branch: main
    stages:
      - execute-remote-command:
          jobs:
            run-ls-on-server:
              environment_variables:
                SERVER_KEY_B64: "{{SECRET:[ssh-key][gocd_deploy_key]}}"
                DISCORD_WEBHOOK: "{{SECRET:[discord-webhook][discord-webhookurl]}}"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                          mkdir -p ./temp
                          echo "$SERVER_KEY_B64" | base64 --decode > ./temp/id_rsa_remote
                          chmod 600 ./temp/id_rsa_remote
                          ssh -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ./temp/id_rsa_remote root@192.168.1.118 'echo "--- 원격 서버 파일 목록 ---"; ls -la'
                          rm -rf ./temp

                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                      - -c
                      - |
                          echo "{
                            \"embeds\": [
                              {
                                \"title\": \"✅ 파이프라인 실행 성공: ${GO_PIPELINE_NAME}\",
                                \"description\": \"**- 스테이지:** ${GO_STAGE_NAME}\\n**- 잡:** ${GO_JOB_NAME}\",
                                \"color\": 3066993
                              }
                            ]
                          }" > payload.json
                
                          curl -H "Content-Type: application/json" -X POST --data-binary @payload.json "$DISCORD_WEBHOOK"
              on_cancel:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                          echo "{
                            \"embeds\": [
                              {
                                \"title\": \"❌ 파이프라인 실행 실패: ${GO_PIPELINE_NAME}\",
                                \"description\": \"**- 스테이지:** ${GO_STAGE_NAME}\\n**- 잡:** ${GO_JOB_NAME}\",
                                \"color\": 15158332
                              }
                            ]
                          }" > payload.json

                          curl -H "Content-Type: application/json" -X POST --data-binary @payload.json "$DISCORD_WEBHOOK"
