# secret-test.gocd.yaml

pipelines:
  show-my-secret-pipeline:
    group: defaultGroup
    timer:
      # GoCD가 사용하는 6자리 Cron 형식(초 분 시 일 월 요일)으로 수정합니다.
      spec: "0 0 0 1 1 ?"
    materials:
      my-git-repo:
        git: https://github.com/your-repo/your-project.git
        branch: main
    stages:
      - display-secret-stage:
          jobs:
            display-secret-job:
              environment_variables:
                MY_SECRET: "{{SECRET:[dal-so-secrets][my_api_key]}}"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - 'echo "API 키 값은 ===> $MY_SECRET"'
