pipelines:
  show-my-secret-pipeline:
    group: defaultGroup

    # 타이머 트리거는 'materials'가 아니라 pipeline 레벨에서 설정합니다.
    timer:
      spec: "0 0 1 1 *"  # 매년 1월 1일 0시

    materials:
      dummy:
        type: git
        url: https://github.com/your/repo.git  # 필수는 아니지만 최소 하나는 있어야 함
        branch: main

    stages:
      - display-secret-stage:
          jobs:
            display-secret-job:
              environment_variables:
                MY_SECRET: "{{SECRET:[dalso-secrets][my-password]}}"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - 'echo "API 키 값은 ===> $MY_SECRET"'
