# gocd.yaml

pipelines:
  remote-server-task:
    group: defaultGroup
    materials:
      my-git-repo2: # 머티리얼에 'my-git-repo'라는 이름을 부여합니다.
        git: https://github.com/dalso0418/gocd-task # 감시할 Git 저장소 주소입니다.
        branch: main # main 브랜치를 감시합니다.
    stages:
      - execute-remote-command:
          jobs:
            run-ls-on-server:
              environment_variables:
                # Base64로 인코딩된 SSH 키를 환경 변수로 주입
                SERVER_KEY_B64: "{{SECRET:[ssh-key][gocd_deploy_key]}}"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo ">> 현재 작업 디렉토리(pwd):"
                        pwd
                        echo ">> 현재 디렉토리 권한(ls -ld .):"
                        ls -ld .
                        echo ">> 현재 사용자(whoami):"
                        whoami
                        echo ">> SERVER_KEY_B64 변수 길이 (0이면 시크릿 주입 실패): $(echo -n "$SERVER_KEY_B64" | wc -c)"
                        
                        echo "1. 임시 디렉토리 생성 시도"
                        mkdir -p ./temp
                        if [ $? -ne 0 ]; then
                          echo "!! 오류: ./temp 디렉토리 생성에 실패했습니다. 현재 작업 디렉토리에 쓰기 권한이 없는 것 같습니다."
                          exit 1
                        fi
                        echo "-> 성공: ./temp 디렉토리 생성 완료."

                        echo "2. 환경 변수에서 키를 디코딩하여 파일로 저장 시도"
                        echo "$SERVER_KEY_B64" | base64 --decode > ./temp/id_rsa_remote
                        if [ ! -s ./temp/id_rsa_remote ]; then
                          echo "!! 오류: 키 파일이 비어있습니다. 시크릿 값(SERVER_KEY_B64)이 올바르게 주입되었는지 확인하세요."
                          exit 1
                        fi
                        echo "-> 성공: 키 파일 생성 완료."

                        echo "3. 키 파일에 올바른 권한(600) 부여 시도"
                        chmod 600 ./temp/id_rsa_remote
                        if [ $? -ne 0 ]; then
                          echo "!! 오류: 키 파일 권한 설정에 실패했습니다."
                          exit 1
                        fi
                        echo "-> 성공: 권한 설정 완료."

                        echo "4. SSH로 원격 서버 접속 시도"
                        ssh -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ./temp/id_rsa_remote user@your-server.com 'echo "--- 원격 서버 접속 성공! ---"; ls -la'
                        if [ $? -ne 0 ]; then
                          echo "!! 오류: SSH 접속에 실패했습니다. 원격 서버의 SSH 설정, 방화벽, 등록된 공개키를 확인하세요."
                        fi
