# gocd.yaml

pipelines:
  remote-server-task:
    group: defaultGroup
    materials:
      my-git-repo2: # 머티리얼에 'my-git-repo'라는 이름을 부여합니다.
        git: https://github.com/dalso0418/gocd-task # 감시할 Git 저장소 주소입니다.
        branch: main # main 브랜치를 감시합니다.
    stages:
      - execute-remote-command:
          jobs:
            run-ls-on-server:
              environment_variables:
                # Base64로 인코딩된 SSH 키를 환경 변수로 주입
                SERVER_KEY_B64: "{{SECRET:[ssh-key][gocd_deploy_key]}}"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "1. 임시 디렉토리 생성"
                        # .ssh 대신 temp 디렉토리 생성
                        mkdir -p ./temp
                        
                        echo "2. 환경 변수에서 키를 디코딩하여 파일로 저장"
                        # temp 디렉토리 아래에 키 파일 생성
                        echo "$SERVER_KEY_B64" | base64 --decode > ./temp/id_rsa_remote
                        
                        echo "3. 키 파일에 올바른 권한(600) 부여 (필수!)"
                        chmod 600 ./temp/id_rsa_remote
                        
                        echo "4. SSH로 원격 서버에 접속하여 'ls -la' 명령어 실행"
                        ## -o StrictHostKeyChecking=no 옵션은 처음 접속 시 호스트 키 확인 프롬프트를 건너뛰게 합니다.
                        ## -F /dev/null 옵션으로 기본 ssh 설정을 무시하고, -i 옵션으로 현재 디렉터리의 키를 명시적으로 사용합니다.
                        ssh -F /dev/null -o StrictHostKeyChecking=no -i ./temp/id_rsa_remote root@192.168.1.225 'echo "--- 원격 서버 파일 목록 ---"; ls -la'
                        
                        echo "작업 완료!"


