# secret-test.gocd.yaml
pipelines:
  show-my-secret-pipeline:
    group: defaultGroup
    # 'materials' 블록에 cron 스케줄러를 설정합니다.
    materials:
      my-cron-timer:
        # 'timer' 머티리얼을 사용합니다.
        type: timer
        # cron 표현식: "분 시 일 월 요일" 순서입니다.
        # '0 0 1 1 *'는 매년 1월 1일 0시 0분을 의미합니다.
        spec: "0 0 1 1 *"
    stages:
      - display-secret-stage:
          jobs:
            display-secret-job:
              environment_variables:
                MY_SECRET: "{{SECRET:[dalso-secrets][my-password]}}"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - 'echo "API 키 값은 ===> $MY_SECRET"'
